# Common Setting
spring:
  application:
    name: blog-backend

server:
  port: 8080
  servlet:
    context-path: /api

# Actuator Configuration
management:
  endpoint:
    web:
      exposure:
        include: health,info,metrics
  endpoints:
    health:
      show-details: always