# Common Setting
spring:
  application:
    name: blog-backend

server:
  port: 8080
  servlet:
    context-path: /api

# Actuator Configuration
management:
  endpoint:
    web:
      exposure:
        include: health,info,metrics
  endpoints:
    health:
      show-details: always

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  packages-to-scan: com.blog.controller
  paths-to-match: /api/**